name: Frontend CI

on:
  pull_request:
    branches: ['main']

env:
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/app
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: npm ci
    - name: Formatting
      run: npm run format:check
    - name: Linting
      run: npm run lint:check
    - name: Build
      run: npm run build

